#!/usr/bin/env bash

## As of Git 2.22 and above
## CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
CURRNET_BRANCH=$(git branch --show-current) # alternative git rev-parse --abbrev-ref HEAD
echo "pushing latest commit to remote repository"
git push origin "$CURRENT_BRANCH"
exit 0
